/* Empty scss module typings placeholders — regenerated by gulp when the full SPFx project is scaffolded. */
declare module "*.module.scss" {
  const styles: { [className: string]: string };
  export default styles;
}
