import "server-only";

import { readFile } from "fs/promises";
import path from "path";

import { getNotificationSettingsSync } from "@/lib/services/notificationConfig";

export const PAVE_EMAIL_LOGO_CID = "pave-logo";

/** Inline logo HTML for emails (paired with cid attachment from loadPaveLogoAttachment). */
export function emailLogoHtml(): string {
  return `<p style="margin:0 0 20px 0;">
<img src="cid:${PAVE_EMAIL_LOGO_CID}" alt="PAVE Training" width="160" style="display:block;width:160px;max-width:100%;height:auto;border:0;" />
</p>`;
}

/** Reads public/brand/pave-logo.png for inline email embedding. */
export async function loadPaveLogoAttachment(): Promise<{
  filename: string;
  contentType: string;
  content: string;
  encoding: "base64";
  contentId: string;
  isInline: true;
} | null> {
  try {
    const logoPath = path.join(process.cwd(), "public", "brand", "pave-logo.png");
    const bytes = await readFile(logoPath);
    return {
      filename: "pave-logo.png",
      contentType: "image/png",
      content: bytes.toString("base64"),
      encoding: "base64",
      contentId: PAVE_EMAIL_LOGO_CID,
      isInline: true,
    };
  } catch (error) {
    console.warn("[notifications] Could not load PAVE logo for email:", error);
    return null;
  }
}

function portalDocumentsUrl(): string | null {
  const settings = getNotificationSettingsSync();
  if (!settings.portalUrl) return null;
  return `${settings.portalUrl.replace(/\/$/, "")}/customer/documents`;
}

function portalMatrixUrl(): string | null {
  const settings = getNotificationSettingsSync();
  if (!settings.portalUrl) return null;
  return `${settings.portalUrl.replace(/\/$/, "")}/customer`;
}

export function documentUploadEmailTemplate(input: {
  companyName: string;
  candidateName?: string | null;
  documentType: string;
}): { subject: string; text: string; html: string } {
  const who = input.candidateName?.trim()
    ? `${input.companyName} / ${input.candidateName.trim()}`
    : input.companyName;
  const docsUrl = portalDocumentsUrl();
  const portalLine = docsUrl
    ? `Please log into the PAVE Training Portal to view it:\n${docsUrl}`
    : "Please log into the PAVE Training Portal to view it.";

  const subject = "New training document available";
  const text = [
    `A new document has been shared for ${who}.`,
    `Document type: ${input.documentType}`,
    "",
    portalLine,
  ].join("\n");

  const html = docsUrl
    ? `<p>A new document has been shared for <strong>${escapeHtml(who)}</strong>.</p>
<p>Document type: <strong>${escapeHtml(input.documentType)}</strong></p>
<p>Please log into the <a href="${escapeHtml(docsUrl)}">PAVE Training Portal</a> to view it.</p>`
    : `<p>A new document has been shared for <strong>${escapeHtml(who)}</strong>.</p>
<p>Document type: <strong>${escapeHtml(input.documentType)}</strong></p>
<p>Please log into the PAVE Training Portal to view it.</p>`;

  return { subject, text, html };
}

export function expiryReminderEmailTemplate(input: {
  companyName: string;
  windowLabel: string;
  candidateCount: number;
}): { subject: string; text: string; html: string } {
  const matrixUrl = portalMatrixUrl();
  const portalLine = matrixUrl
    ? `Please log into the PAVE Training Portal to review the Training Matrix:\n${matrixUrl}`
    : "Please log into the PAVE Training Portal to review the Training Matrix.";

  const subject = "Training expiry reminder";
  const text = [
    `Training records are expired or due soon for ${input.companyName}.`,
    `Reminder window: ${input.windowLabel}`,
    `Candidates affected: ${input.candidateCount}`,
    "",
    portalLine,
  ].join("\n");

  const html = matrixUrl
    ? `<p>Training records are expired or due soon for <strong>${escapeHtml(input.companyName)}</strong>.</p>
<p>Reminder window: <strong>${escapeHtml(input.windowLabel)}</strong><br/>
Candidates affected: <strong>${input.candidateCount}</strong></p>
<p>Please log into the <a href="${escapeHtml(matrixUrl)}">PAVE Training Portal</a> to review the Training Matrix.</p>`
    : `<p>Training records are expired or due soon for <strong>${escapeHtml(input.companyName)}</strong>.</p>
<p>Reminder window: <strong>${escapeHtml(input.windowLabel)}</strong><br/>
Candidates affected: <strong>${input.candidateCount}</strong></p>
<p>Please log into the PAVE Training Portal to review the Training Matrix.</p>`;

  return { subject, text, html };
}

export function adminAlertEmailTemplate(input: {
  title: string;
  detail: string;
}): { subject: string; text: string; html: string } {
  const subject = `PAVE Admin alert: ${input.title}`;
  const text = [
    input.title,
    "",
    input.detail,
    "",
    "This alert was generated by the PAVE Training Portal.",
  ].join("\n");
  const html = `<p><strong>${escapeHtml(input.title)}</strong></p>
<p>${escapeHtml(input.detail)}</p>
<p>This alert was generated by the PAVE Training Portal.</p>`;
  return { subject, text, html };
}

/**
 * Portal invitation email — used for User / Customer / Training Manager /
 * Supervisor / Candidate invites. Client-approved rule: every invitation MUST
 * include Company and Role on their own lines so the recipient knows exactly
 * which company they are being granted access to and in what capacity.
 * Generic invites without a Company are rejected by `sendPortalInviteNotification`.
 */
export function portalInviteEmailTemplate(input: {
  displayName?: string | null;
  companyName?: string | null;
  roleLabel?: string | null;
}): { subject: string; text: string; html: string } {
  const settings = getNotificationSettingsSync();
  const portalUrl = settings.portalUrl?.replace(/\/$/, "") || null;
  const loginUrl = portalUrl ? `${portalUrl}/login` : null;
  const who = input.displayName?.trim() || "there";
  // Fallback labels only appear if a call site slipped past the send-time
  // guard — we still render the field so the recipient can see the drift.
  const company = input.companyName?.trim() || "— not set —";
  const role = input.roleLabel?.trim() || "— not set —";

  const subject = "You're invited to the PAVE Training Portal";
  const text = [
    `Hi ${who},`,
    "",
    "You have been invited to the PAVE Training Portal.",
    "",
    "Company:",
    company,
    "",
    "Role:",
    role,
    "",
    loginUrl
      ? `Sign in here:\n${loginUrl}`
      : "Please sign in using the portal link provided by your training provider.",
    "",
    "Use your work email with Microsoft sign-in, or request a one-time code from the login screen. If your organisation uses multi-factor authentication, you will be prompted as usual.",
  ].join("\n");

  const html = `${emailLogoHtml()}<p>Hi ${escapeHtml(who)},</p>
<p>You have been invited to the <strong>PAVE Training Portal</strong>.</p>
<p><strong>Company:</strong><br/>${escapeHtml(company)}</p>
<p><strong>Role:</strong><br/>${escapeHtml(role)}</p>
${
  loginUrl
    ? `<p><a href="${escapeHtml(loginUrl)}">Sign in to the portal</a></p>`
    : `<p>Please sign in using the portal link provided by your training provider.</p>`
}
<p>Use your work email with Microsoft sign-in, or request a one-time code from the login screen. If your organisation uses multi-factor authentication, you will be prompted as usual.</p>`;

  return { subject, text, html };
}

/**
 * Client-approved booking confirmation — sent when Tentative → Confirmed.
 */
export function bookingConfirmedEmailTemplate(input: {
  trainingManagerName?: string | null;
  eventTitle: string;
  dateLabel: string;
  timeLabel: string;
  location?: string | null;
}): { subject: string; text: string; html: string } {
  const settings = getNotificationSettingsSync();
  const portalUrl = settings.portalUrl?.replace(/\/$/, "") || null;
  const eventsUrl = portalUrl ? `${portalUrl}/customer/events` : null;
  const who = input.trainingManagerName?.trim() || "there";
  const title = input.eventTitle.trim() || "Training booking";
  const location = input.location?.trim() || "—";
  const contact = "Info@pavetraining.co.uk";

  const subject = `Training booking confirmed — ${title}`;
  const text = [
    `Hi ${who},`,
    "",
    "Your training booking is confirmed.",
    "",
    `Event: ${title}`,
    `Date: ${input.dateLabel}`,
    `Time: ${input.timeLabel}`,
    `Location: ${location}`,
    "",
    eventsUrl
      ? `View in the PAVE Training Portal:\n${eventsUrl}`
      : "View in the PAVE Training Portal.",
    "",
    "This email includes a calendar invite (.ics). Open / Accept it in Outlook to add the booking to your calendar.",
    "",
    "Any questions please contact:",
    contact,
    "",
    "Cancellation terms:",
    "100% fee if cancelled within 10 days of the course start date.",
    "50% fee if cancelled 11-20 days before the course start date.",
    "These charges will not apply if the course is rebooked for alternative dates.",
    "",
    "Kind regards,",
    "PAVE Training",
  ].join("\n");

  const html = `<p>Hi ${escapeHtml(who)},</p>
<p>Your training booking is confirmed.</p>
<p><strong>Event:</strong> ${escapeHtml(title)}<br/>
<strong>Date:</strong> ${escapeHtml(input.dateLabel)}<br/>
<strong>Time:</strong> ${escapeHtml(input.timeLabel)}<br/>
<strong>Location:</strong> ${escapeHtml(location)}</p>
${
  eventsUrl
    ? `<p>View in the <a href="${escapeHtml(eventsUrl)}">PAVE Training Portal</a>.</p>`
    : `<p>View in the PAVE Training Portal.</p>`
}
<p>This email includes a calendar invite (<strong>.ics</strong>). Open or Accept it in Outlook to add the booking to your calendar.</p>
<p>Any questions please contact:<br/>
<a href="mailto:info@pavetraining.co.uk">${escapeHtml(contact)}</a></p>
<p><strong>Cancellation terms:</strong><br/>
100% fee if cancelled within 10 days of the course start date.<br/>
50% fee if cancelled 11-20 days before the course start date.<br/>
These charges will not apply if the course is rebooked for alternative dates.</p>
<p>Kind regards,<br/>PAVE Training</p>`;

  return { subject, text, html };
}

export function testEmailTemplate(): {
  subject: string;
  text: string;
  html: string;
} {
  const settings = getNotificationSettingsSync();
  const subject = "PAVE Training Portal — test notification";
  const text = [
    "This is a test notification from the PAVE Training Portal.",
    settings.portalUrl ? `Portal: ${settings.portalUrl}` : "",
    `Sent at: ${new Date().toISOString()}`,
  ]
    .filter(Boolean)
    .join("\n");
  const html = settings.portalUrl
    ? `<p>This is a test notification from the PAVE Training Portal.</p>
<p>Portal: <a href="${escapeHtml(settings.portalUrl)}">${escapeHtml(settings.portalUrl)}</a></p>
<p>Sent at: ${escapeHtml(new Date().toISOString())}</p>`
    : `<p>This is a test notification from the PAVE Training Portal.</p>
<p>Sent at: ${escapeHtml(new Date().toISOString())}</p>`;
  return { subject, text, html };
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
