import "server-only";

import { getNotificationSettingsSync } from "@/lib/services/notificationConfig";

function portalDocumentsUrl(): string | null {
  const settings = getNotificationSettingsSync();
  if (!settings.portalUrl) return null;
  return `${settings.portalUrl.replace(/\/$/, "")}/customer/documents`;
}

function portalMatrixUrl(): string | null {
  const settings = getNotificationSettingsSync();
  if (!settings.portalUrl) return null;
  return `${settings.portalUrl.replace(/\/$/, "")}/customer`;
}

export function documentUploadEmailTemplate(input: {
  companyName: string;
  candidateName?: string | null;
  documentType: string;
}): { subject: string; text: string; html: string } {
  const who = input.candidateName?.trim()
    ? `${input.companyName} / ${input.candidateName.trim()}`
    : input.companyName;
  const docsUrl = portalDocumentsUrl();
  const portalLine = docsUrl
    ? `Please log into the PAVE Training Portal to view it:\n${docsUrl}`
    : "Please log into the PAVE Training Portal to view it.";

  const subject = "New training document available";
  const text = [
    `A new document has been shared for ${who}.`,
    `Document type: ${input.documentType}`,
    "",
    portalLine,
  ].join("\n");

  const html = docsUrl
    ? `<p>A new document has been shared for <strong>${escapeHtml(who)}</strong>.</p>
<p>Document type: <strong>${escapeHtml(input.documentType)}</strong></p>
<p>Please log into the <a href="${escapeHtml(docsUrl)}">PAVE Training Portal</a> to view it.</p>`
    : `<p>A new document has been shared for <strong>${escapeHtml(who)}</strong>.</p>
<p>Document type: <strong>${escapeHtml(input.documentType)}</strong></p>
<p>Please log into the PAVE Training Portal to view it.</p>`;

  return { subject, text, html };
}

export function expiryReminderEmailTemplate(input: {
  companyName: string;
  windowLabel: string;
  candidateCount: number;
}): { subject: string; text: string; html: string } {
  const matrixUrl = portalMatrixUrl();
  const portalLine = matrixUrl
    ? `Please log into the PAVE Training Portal to review the Training Matrix:\n${matrixUrl}`
    : "Please log into the PAVE Training Portal to review the Training Matrix.";

  const subject = "Training expiry reminder";
  const text = [
    `Training records are expired or due soon for ${input.companyName}.`,
    `Reminder window: ${input.windowLabel}`,
    `Candidates affected: ${input.candidateCount}`,
    "",
    portalLine,
  ].join("\n");

  const html = matrixUrl
    ? `<p>Training records are expired or due soon for <strong>${escapeHtml(input.companyName)}</strong>.</p>
<p>Reminder window: <strong>${escapeHtml(input.windowLabel)}</strong><br/>
Candidates affected: <strong>${input.candidateCount}</strong></p>
<p>Please log into the <a href="${escapeHtml(matrixUrl)}">PAVE Training Portal</a> to review the Training Matrix.</p>`
    : `<p>Training records are expired or due soon for <strong>${escapeHtml(input.companyName)}</strong>.</p>
<p>Reminder window: <strong>${escapeHtml(input.windowLabel)}</strong><br/>
Candidates affected: <strong>${input.candidateCount}</strong></p>
<p>Please log into the PAVE Training Portal to review the Training Matrix.</p>`;

  return { subject, text, html };
}

export function adminAlertEmailTemplate(input: {
  title: string;
  detail: string;
}): { subject: string; text: string; html: string } {
  const subject = `PAVE Admin alert: ${input.title}`;
  const text = [
    input.title,
    "",
    input.detail,
    "",
    "This alert was generated by the PAVE Training Portal.",
  ].join("\n");
  const html = `<p><strong>${escapeHtml(input.title)}</strong></p>
<p>${escapeHtml(input.detail)}</p>
<p>This alert was generated by the PAVE Training Portal.</p>`;
  return { subject, text, html };
}

export function portalInviteEmailTemplate(input: {
  displayName?: string | null;
  companyName?: string | null;
  roleLabel?: string | null;
}): { subject: string; text: string; html: string } {
  const settings = getNotificationSettingsSync();
  const portalUrl = settings.portalUrl?.replace(/\/$/, "") || null;
  const loginUrl = portalUrl ? `${portalUrl}/login` : null;
  const who = input.displayName?.trim() || "there";
  const company = input.companyName?.trim() || null;
  const role = input.roleLabel?.trim() || null;

  const subject = "You're invited to the PAVE Training Portal";
  const text = [
    `Hi ${who},`,
    "",
    "You have been invited to the PAVE Training Portal.",
    company ? `Company: ${company}` : null,
    role ? `Role: ${role}` : null,
    "",
    loginUrl
      ? `Sign in here:\n${loginUrl}`
      : "Please sign in using the portal link provided by your training provider.",
    "",
    "Use your work email with Microsoft sign-in. If your organisation uses multi-factor authentication, you will be prompted as usual.",
  ]
    .filter((line): line is string => line !== null)
    .join("\n");

  const html = `<p>Hi ${escapeHtml(who)},</p>
<p>You have been invited to the <strong>PAVE Training Portal</strong>.</p>
${company ? `<p>Company: <strong>${escapeHtml(company)}</strong></p>` : ""}
${role ? `<p>Role: <strong>${escapeHtml(role)}</strong></p>` : ""}
${
  loginUrl
    ? `<p><a href="${escapeHtml(loginUrl)}">Sign in to the portal</a></p>`
    : `<p>Please sign in using the portal link provided by your training provider.</p>`
}
<p>Use your work email with Microsoft sign-in. If your organisation uses multi-factor authentication, you will be prompted as usual.</p>`;

  return { subject, text, html };
}

/**
 * Client-approved booking confirmation — sent when Tentative → Confirmed.
 */
export function bookingConfirmedEmailTemplate(input: {
  trainingManagerName?: string | null;
  eventTitle: string;
  dateLabel: string;
  timeLabel: string;
  location?: string | null;
}): { subject: string; text: string; html: string } {
  const settings = getNotificationSettingsSync();
  const portalUrl = settings.portalUrl?.replace(/\/$/, "") || null;
  const eventsUrl = portalUrl ? `${portalUrl}/customer/events` : null;
  const who = input.trainingManagerName?.trim() || "there";
  const title = input.eventTitle.trim() || "Training booking";
  const location = input.location?.trim() || "—";
  const contact = "Info@pavetraining.co.uk";

  const subject = `Training booking confirmed — ${title}`;
  const text = [
    `Hi ${who},`,
    "",
    "Your training booking is confirmed.",
    "",
    `Event: ${title}`,
    `Date: ${input.dateLabel}`,
    `Time: ${input.timeLabel}`,
    `Location: ${location}`,
    "",
    eventsUrl
      ? `View in the PAVE Training Portal:\n${eventsUrl}`
      : "View in the PAVE Training Portal.",
    "",
    "Any questions please contact:",
    contact,
    "",
    "Cancellation terms:",
    "100% fee if cancelled within 10 days of the course start date.",
    "50% fee if cancelled 11-20 days before the course start date.",
    "These charges will not apply if the course is rebooked for alternative dates.",
    "",
    "Kind regards,",
    "PAVE Training",
  ].join("\n");

  const html = `<p>Hi ${escapeHtml(who)},</p>
<p>Your training booking is confirmed.</p>
<p><strong>Event:</strong> ${escapeHtml(title)}<br/>
<strong>Date:</strong> ${escapeHtml(input.dateLabel)}<br/>
<strong>Time:</strong> ${escapeHtml(input.timeLabel)}<br/>
<strong>Location:</strong> ${escapeHtml(location)}</p>
${
  eventsUrl
    ? `<p>View in the <a href="${escapeHtml(eventsUrl)}">PAVE Training Portal</a>.</p>`
    : `<p>View in the PAVE Training Portal.</p>`
}
<p>Any questions please contact:<br/>
<a href="mailto:info@pavetraining.co.uk">${escapeHtml(contact)}</a></p>
<p><strong>Cancellation terms:</strong><br/>
100% fee if cancelled within 10 days of the course start date.<br/>
50% fee if cancelled 11-20 days before the course start date.<br/>
These charges will not apply if the course is rebooked for alternative dates.</p>
<p>Kind regards,<br/>PAVE Training</p>`;

  return { subject, text, html };
}

export function testEmailTemplate(): {
  subject: string;
  text: string;
  html: string;
} {
  const settings = getNotificationSettingsSync();
  const subject = "PAVE Training Portal — test notification";
  const text = [
    "This is a test notification from the PAVE Training Portal.",
    settings.portalUrl ? `Portal: ${settings.portalUrl}` : "",
    `Sent at: ${new Date().toISOString()}`,
  ]
    .filter(Boolean)
    .join("\n");
  const html = settings.portalUrl
    ? `<p>This is a test notification from the PAVE Training Portal.</p>
<p>Portal: <a href="${escapeHtml(settings.portalUrl)}">${escapeHtml(settings.portalUrl)}</a></p>
<p>Sent at: ${escapeHtml(new Date().toISOString())}</p>`
    : `<p>This is a test notification from the PAVE Training Portal.</p>
<p>Sent at: ${escapeHtml(new Date().toISOString())}</p>`;
  return { subject, text, html };
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
